aio/content/marketing/index.html, aio/content/navigation.json, aio/src/app/app.component.html, aio/src/app/layout/footer/footer.component.html, aio/src/app/search/search-box/search-box.component.ts, aio/src/index.html
La página de inicio está en inglés.
Issue Number: N/A
La página de inicio está en castellano.
=> docs: traducir página de inicio, navegación, cuadro de búsqueda y piede página

aio/content/marketing/index.html
The way to express the ideas is in the "usted" way in spanish.
Issue Number: N/A
Expressing the ideas in the way of "tu" in spanish in the homepage
=> fix(docs): changed the way to express the idea in the homepage

aio/content/guide/app-shell.md
Issue Number: https://github.com/angular-hispano/angular/issues/19
Translation of the official documentation for app shell into Spanish.
=> docs: translate the app-shell.md file

README.md
Traducción del README.md al español.
Issue Number: N/A
=> Traducción del README.md

aio/content/guide/cheatsheet.md
Issue Number: https://github.com/angular-hispano/angular/issues/32
Translation of the official documentation for cheat sheet into Spanish.
=> docs: translate cheatsheet.md file to Spanish

.github/PULL_REQUEST_TEMPLATE.md
Plantillas en ingles, traducidas en espanol
Issue Number: #45
=> fix(pr): template

aio/content/guide/accessibility.md
Traducido el apartado "Accesibilidad en Angular". Pendiente de revisión.
=> Traducido: accessibility.md

aio/content/marketing/docs.en.md, aio/content/marketing/docs.md
Se traduce la guia de Introduccion a la documentacion de Angular
La pagina de intrtoducción a la documentación de angular esta en ingles
La pagina de intrtoducción a la documentación de angular traducida al español
closes #59
=> docs: traducida la guia Intro

aio/content/guide/comparing-observables.en.md, aio/content/guide/comparing-observables.md
El fichero comparing-observables está en inglés.
El fichero comparing-observables es traducido a español.
Closes #34
=> docs: translate comparing-observables.md

aio/content/marketing/docs.md
- enlace a las guías de MDN en español
- use el enlace CoC correcto
Relates to #60. Relates to #59.
=> docs: enlace a las guías de MDN en español

README.en.md, README.md
- hacer que el archivo README.md sea más aplicable a este repositorio
- aclarar que el trabajo de bugs / características debe realizarse upstream
- cambiar los enlaces para que apunten dentro del repositorio en lugar de a la web
=> docs: hacer que el archivo README.md sea más aplicable a este repositorio

aio/README.md
traducido el archivo readme-> "aio/readme.md"
Archivo en inglés traducido al español ->issue #44
=> build:translate readme.md

aio/content/guide/attribute-binding.en.md, aio/content/guide/attribute-binding.md
Issue: https://github.com/angular-hispano/angular/issues/25
=> docs: translate guide/attribute-binding.md file to Spanish

CONTRIBUTING.md
Actualiza el archivo CONTRIBUTING.md basado en las observaciones de la revisión de código https://github.com/angular-hispano/angular/pull/58#pullrequestreview-468024575
La sección CLA tiene una descripción del proceso de Angular Team
La sección CLA tiene una descripción del proceso de Angular Hispano
Fix #48
=> docs: actualiza el archivo CONTRUBUTING.md

aio/content/guide/glossary.md
Library esta traducido como biblioteca
Library esta traducido como librería
=> docs: glossary.md change biblioteca to librería

aio/content/tutorial/toh-pt6.en.md, aio/content/tutorial/toh-pt6.md
El contenido se muestra en ingles
El contenido de la parte 6 del tour de héroes se muestra es español
Fix #79
=> docs: translate tutorial/toh-pt6.md

aio/content/guide/ajs-quick-reference.md, aio/content/guide/architecture.en.md, aio/content/guide/architecture.md, aio/src/app/custom-elements/live-example/live-example.component.html
La página de Introducción a los conceptos básicos de Angular está en inglés.
La página de Introducción a los conceptos básicos de Angular está en español.
closes #24
=> docs: architecture.md traducido al español

aio/content/navigation.json
La sección de navegación ahora se muestra en español
La sección de navegación ahora se muestra en español
Fix #4
=> docs: translate aio/content/navigation.json 

aio/content/tutorial/index.en.md, aio/content/tutorial/index.md
El index de Tour of Heroes esta traducida
El index de Tour of Heroes esta traducida
Fix #72
=> docs: translate tutorial/index.md

aio/content/marketing/docs.md
- A algunas palabras le faltan tildes y hay una oración con forma de expresión "usted".
Palabras con tilde y forma de expresión "tu".
Fix #92
=> docs: actualiza el archivo docs.md

aio/content/guide/architecture-services.en.md, aio/content/guide/architecture-services.md
La página de arquitectura de servicios de Angular está en inglés.
La página de arquitectura de servicios de Angular está en español e inglés.
closes #23
=> docs: architecture-services.md traducido al español

aio/content/tutorial/toh-pt6.en.md, aio/content/tutorial/toh-pt6.md
```
warn:    Dangling Links Found in "tutorial/toh-pt6.en.json":
- tutorial/toh-pt6#heroes-and-http
warn:    Dangling Links Found in "tutorial/toh-pt6.json":
- tutorial/toh-pt6#heroes-and-http
error:   Error: 2 unmatched links
at Object.$process (/Users/splaktar/Git/angular-hispano/angular/aio/node_modules/dgeni-packages/base/processors/checkAnchorLinks.js:88:17)
at /Users/splaktar/Git/angular-hispano/angular/aio/node_modules/dgeni/lib/Dgeni.js:183:54
at _fulfilled (/Users/splaktar/Git/angular-hispano/angular/aio/node_modules/q/q.js:854:54)
at /Users/splaktar/Git/angular-hispano/angular/aio/node_modules/q/q.js:883:30
at Promise.promise.promiseDispatch …
```
=> docs: arreglar enlaces colgantes en toh-pt6

.github/PULL_REQUEST_TEMPLATE.md
Para mi es mas descriptivo si lo tomamos en pasado como por ejemplo que el usuario diga que probo todo antes de subirlo
Esta planteado a futuro 
Esta planteado en pasado como un acuerdo de que el usuario previamente siguió determinados pasos
=> Cambios en el template de Verificación de PR

aio/content/guide/architecture-modules.en.md, aio/content/guide/architecture-modules.md
Se traduce Introducción a los módulos
La página Introducción a los módulos está en inglés.
La página Introducción a los módulos traducido al español.
closes #21
=> docs: architecture-modules.md traducido al español

CODE_OF_CONDUCT.md
- Se utiliza el breve código de conducta de la comunidad Angular.
- Se utiliza el código de conducta más completo de la comunidad Angular Hispano.
=> docs: actualización del código de conducta de Angular Hispano

aio/content/marketing/about.html
- [x ] Cambios en el contenido de la documentación
El contenido de
=> docs: translate marketing/about.html to spanish #7

aio/content/marketing/events.html
El archivo marketing/events.html se encuentra en inglés 
El archivo marketing/events.html se tradujo al español
fix #99
=> traducción marketing/events.html

aio/content/marketing/analytics.en.md, aio/content/marketing/analytics.md
El archivo se encuentra en inglés  
El archivo se encuentra en español 
fix #96
=> analytics.md traducido

aio/content/marketing/contribute.html
el archivo contribute.hmtl se encuentra en inglés 
el archivo contribute.hmtl se encuentra en español
fix #98
=> contribute.hmtl traducido

aio/content/guide/testing-pipes.en.md, aio/content/guide/testing-pipes.md
Actualmente el archivo testing-pipes.md está en Inglés solamente.
El archivo en Inglés pasa a tener extensión testing-pipes.en.md y el archivo testing-pipes.md pasa a estar traducido al Español.
Fix #229
=> Docs traducción de testing-pipes.md

aio/content/guide/complex-animation-sequences.en.md, aio/content/guide/complex-animation-sequences.md
Traducción del fichero complex animation sequences.
Issue: https://github.com/angular-hispano/angular/issues/35
Archivo en inglés.
Archivo en inglés traducido al español.
=> docs: translate complex animation sequences

aio/content/guide/template-statements.en.md, aio/content/guide/template-statements.md
El archivo `template-statement.md` está en ingles
El archivo `template-statement.md` está en español
Fix #221
=> docs: Translate template-statement.md from English to Spanish

aio/content/guide/bootstrapping.en.md, aio/content/guide/bootstrapping.md
Issue https://github.com/angular-hispano/angular/issues/28
=> docs: translate guide/bootstrapping.md to spanish

aio/content/guide/set-document-title.en.md, aio/content/guide/set-document-title.md
Traducir: guide/set-document-title.md #215
Fix: #215
=> Traducir: guide/set-document-title.md #215

aio/content/marketing/resources.html
El contenido se muestra en ingles
El contenido de marketing/resources.html traducido muestra es español
Fix #104
=> marketing-resources-docs traducido

aio/content/guide/setup-local.en.md, aio/content/guide/setup-local.md
Translate #116 
El archivo `setup-local.md` está en ingles
El archivo `setup-local.md` está en español
=> docs: Translate setup-local.md from English to Spanish

aio/content/tutorial/toh-pt4.en.md, aio/content/tutorial/toh-pt4.md
El contenido se muestra en ingles
El contenido de la parte 4 del tour de héroes se muestra es español
Fix #77
=> docs: translate tutorial/toh-pt4.md 

aio/content/guide/testing-services.en.md, aio/content/guide/testing-services.md
Translate #230
El archivo `testing-services.md` está en ingles
El archivo `testing-services.md` está en español
=> docs: Transalate testing-services from English to Spanish

.github/PULL_REQUEST_TEMPLATE.md, aio/diccionario-de-términos.md
No hay un archivo donde se guarden el diccionario de términos
Se guardan las traducciones sugeridas en el issue https://github.com/angular-hispano/angular/issues/9 en un archivo .md
=> Agregar archivo: aio/diccionario-de-términos.md

aio/content/marketing/contributors.json, aio/src/styles/2-modules/_buttons.scss, aio/tests/e2e/src/app.e2e-spec.ts
- solucione el problema con el tamaño del botón que causa que se elimine el relleno
=> docs: traducir nombre de Collaborators group

aio/content/tutorial/toh-pt3.en.md, aio/content/tutorial/toh-pt3.md
El contenido se muestra en ingles
El contenido de la parte 3 del tour de héroes se muestra es español
Fix #76
=> docs: translate tutorial/toh-pt3.md

aio/content/marketing/features.html
=> Traducir: marketing/features.html

aio/tests/e2e/src/app.e2e-spec.ts
- aio e2e está roto
- arreglar aio e2e
- check for translated /features page content and title
Fixes #296. Relates to #292.
=> test: fix aio e2e

aio/content/marketing/resources-contributing.md
El archivo se encuentra en inglés 
El archivo se encontraba en ingles ahora esta traducido al español
Fix #103
=> Traducido marketing-resources-contributing-docs

aio/tests/e2e/src/app.e2e-spec.ts
=> docs: fix error in e2e with /tutorial

aio/content/guide/complex-animation-sequences.md
Carácter extraño en el subtitulo hace que se vea mal
Se removió el caracter raro.
=> Solucionar: guide/complex-animation-sequences.mddocs: fix space in subtitle

aio/content/marketing/features.html, aio/tests/e2e/src/app.e2e-spec.ts
- El símbolo "&" está representando una letra "y". Que para consistencia de la traducción a español sería conveniente cambiarlo. 
- Se encuentra una oración en forma de expresión "usted".
- Representación singular API.
- Se remplaza el símbolo "&" por la letra "y". 
- Se cambia de la forma de expresión "usted" a "tu".
- Se agrega el plural de API (APIs) como en el archivo original.
=> docs: remplaza símbolo "&" por letra "y"

aio/content/guide/web-worker.en.md, aio/content/guide/web-worker.md
=> feat(docs): web worker translations

aio/content/guide/setup-local.md
- A algunas palabras le faltan tildes.
- Se encuentran algunos errores de ortografía.
- Hay algunas oraciones escritas en forma de expresión de "usted".
- Se agregan tildes a algunas palabras. 
- Se corrigen algunos typos.
- Se cambia la forma de expresión de "usted" a "tu".
=> docs: corrige typos y agrega tildes

aio/content/guide/testing-attribute-directives.en.md, aio/content/guide/testing-attribute-directives.md
Actualmente el archivo testing-attribute-directives.md está en Inglés solamente.
El archivo en Inglés pasa a tener extensión testing-attribute-directives.en.md y el archivo testing-attribute-directives.md pasa a estar traducido al Español.
Fix #225
=> Docs traducción de testing-attribute-directives.md

aio/content/guide/testing-code-coverage.en.md, aio/content/guide/testing-code-coverage.md
Actualmente el archivo testing-code-coverage.md está en Inglés solamente.
El archivo en Inglés pasa a tener extensión testing-code-coverage.md.en.md y el archivo testing-code-coverage.md.md pasa a estar traducido al Español.
Fix #226
=> Docs traducción de testing-code-coverage.md

aio/content/guide/migration-update-module-and-target-compiler-options.en.md, aio/content/guide/migration-update-module-and-target-compiler-options.md
La página "Update module and target compiler options migration" de la documentación solo está en inglés
Archivo traducido al español
Closes #212
=> Traducir: guide/migration-update-module-and-target-compiler-options.md

aio/content/start/start-routing.en.md, aio/content/start/start-routing.md
start-routing.md se encuentra en inglés
Los archivos se ha traducido al español  
<span class="issue-keyword tooltipped tooltipped-se" aria-label="This pull request closes issue #100.">feat(lang): </span> [#118](https://github.com/angular-hispano/angular/issues/118)
=> docs: start-routing Traducido al Español

aio/content/guide/web-worker.md
Algunas oraciones se encuentran escritas en forma de expresión "usted".
Se han corregido las oraciones para que estén expresadas en forma de "tu"
=> docs: cambia forma de expresión de algunas oraciones

aio/content/guide/glossary.md
- Formas de expresión de usted
- Typos
- Se cambió de la forma de expresión "usted" a la forma de expresión "tu".
- Se corrigieron algunos typos
- Se corrigieron algunas traducciones
=> docs: corrige formas de expresion y traducciones del archivo glosary.md

aio/content/guide/template-statements.md
En una parte de la documentación tiene comillas dobles y va simples.
Las comillas se cambiaron a simples.
https://github.com/angular-hispano/angular/issues/307
=> Solucionar: guide/template-statements.md

aio/content/guide/template-syntax.en.md, aio/content/guide/template-syntax.md
=> Traducir: template-syntax.md

aio/content/tutorial/index.md
Oración escrita en forma de expresión "usted".
Oración escrita en forma de expresión "tu".
=> docs: cambia forma de expresión en tutorial de héroes index.md

aio/content/tutorial/toh-pt5.md
En el archivo top-ph5.md algunas oraciones están escritas en forma de expresión "usted".
Archivo top-ph5.md escrito en forma de expresión "tu", se mejoran algunas traducciones y se corrigen algunos typos.
=> docs: corrige y cambia forma de expresión en el archivo top-ph5.md

aio/content/guide/libraries.en.md, aio/content/guide/libraries.md
aio/content/guide/libraries.md
=> docs: translate libraries.md

aio/content/marketing/presskit.html
=> docs: fix presskit layout

aio/content/guide/migration-solution-style-tsconfig.en.md, aio/content/guide/migration-solution-style-tsconfig.md
aio\content\guide\migration-solution-style-tsconfig.md
=> docs: translate migration-solution-style-tsconfig.md

aio/content/guide/binding-syntax.en.md, aio/content/guide/binding-syntax.md
el documento : content\guide\binding-syntax.md no tiene su versión en español
traducir el documento: content\guide\binding-syntax.md
=> docs: translate-first-revision content\guide\binding-syntax.md

aio/content/guide/route-animations.en.md, aio/content/guide/route-animations.md
Archivo route-animation se encuentra solamente en inglés
Archivo route-animation en inglés fue traducido al español
=> docs: traducción archivo route-animations

aio/content/guide/http.md, aio/content/guide/rx-library.en.md, aio/content/guide/rx-library.md
=> docs: translate rx-library.md

aio/content/guide/schematics.en.md, aio/content/guide/schematics.md
Archivo schematics.md se encuentra solamente en inglés
Archivo schematics.md en inglés fue traducido al español
Fixes: #160
=> docs: Traducir: guide/schematics.md (#160)

aio/content/cli/usage-analytics-gathering.en.md, aio/content/cli/usage-analytics-gathering.md
Traducción del archivo al español
=> docs(docs-infra): traducción de cli/usage-analytics-gathering.md

aio/content/cli/index.en.md, aio/content/cli/index.md
=> docs(docs-infra): traducción de cli/index.md (#331)

aio/content/start/start-deployment.en.md, aio/content/start/start-deployment.md
=> docs: traduce archivo start/start-deployment.md (#121)

aio/content/guide/architecture-components.en.md, aio/content/guide/architecture-components.md
aio\content\guide\architecture-components.md
=> docs: translate architecture-components.md

aio/content/guide/router-tutorial.en.md, aio/content/guide/router-tutorial.md
Hice la traducción del ingles hacia el español del archivo router-tutorial.md
Fix #332
El archivo router-tutorial.md estaba solo en ingles.
El archivo con el nombre router-tutorial.md ahora esta en español y la versión en ingles tiene el nombre de router-tutorial-en-md
Fixes: #332
=> docs(docs-infra): traducción del archivo router-tutorial.md

aio/content/guide/observables-in-angular.en.md, aio/content/guide/observables-in-angular.md
observables-in-angular.md estaba en ingles
Fixes: #145
=> docs(docs-infra): translate observables-in-angular.md

aio/content/guide/ivy-compatibility.en.md, aio/content/guide/ivy-compatibility.md
Archivo ivy-compatibility.md se encuentra solamente en inglés
Archivo ivy-compatibility.md en inglés fue traducido al español
Fixes #195
=> docs: Traducir: guide/ivy-compatibility.md (angular-hispano#195)

aio/content/start/start-forms.en.md, aio/content/start/start-forms.md
Esta archivo de la documentación está en inglés
Traducción al español
=> docs: translate start/start-forms.md

aio/content/guide/migration-injectable.en.md, aio/content/guide/migration-injectable.md
Fixes #203 
Archivo migration-injectable se encuentra solamente en inglés
Archivo migration-injectable en inglés fue traducido al español
=> docs(docs-infra): traducción del archivo migration-injectable.md

aio/content/guide/lazy-loading-ngmodules.en.md, aio/content/guide/lazy-loading-ngmodules.md
=> docs(platform-browser-dynamic): traducir lazy-loading-ngmodules

aio/content/guide/dynamic-component-loader.en.md, aio/content/guide/dynamic-component-loader.md
Traducción del archivo al español
Fixes: #137
=> docs(docs-infra): traducción de guide/dynamic-component-loader.md

aio/content/guide/dependency-injection.en.md, aio/content/guide/dependency-injection.md
Se realizo traduccion a español de /content/guide/dependency-injection.md
Fix #169
Issue Number: 169
=> docs(docs-infra): traduccion de dependency-injection.md

aio/diccionario-de-términos.md
Actualmente no se cuenta con los siguientes términos en el diccionario:
- Snippet
- Tree-Shakable
Se agregan los siguientes términos al diccionario:
- Snippet
- Tree-Shakable
=> docs(docs-infra): agregado de términos al diccionario

aio/content/guide/accessibility.md
Link en Markdown mal formateado, como también traducción no necesariamente correcta.
Se agregó el link apuntando a la sección correspondiente y se corrige parte de la traducción.
Link al issue #416
=> docs(a11y): add missing guide reference
